@extends('layouts.admin')
@section('title', $option->exists ? 'Edytuj opcję' : 'Dodaj opcję')
@section('content')
<a class="text-sm text-[#D51A70]" href="{{ route('admin.options.index') }}">← Opcje i ceny</a><h1 class="mt-2 text-3xl font-bold">{{ $option->exists ? 'Edytuj opcję' : 'Dodaj opcję' }}</h1>
<form method="post" action="{{ $option->exists ? route('admin.options.update', $option) : route('admin.options.store') }}" class="mt-6 max-w-4xl rounded-xl bg-white p-6 shadow-sm">@csrf @if($option->exists) @method('put') @endif
<div class="grid gap-4 sm:grid-cols-2"><label class="text-sm">Nazwa<input name="name" value="{{ old('name', $option->name) }}" required class="mt-1 w-full rounded border p-2"></label><label class="text-sm">Kod<input name="code" value="{{ old('code', $option->code) }}" required class="mt-1 w-full rounded border p-2"></label><label class="text-sm">Typ pola<select name="input_type" class="mt-1 w-full rounded border p-2"><option value="select" @selected(old('input_type', $option->input_type) === 'select')>Jedna wartość</option><option value="multi" @selected(old('input_type', $option->input_type) === 'multi')>Wiele wartości</option></select></label><label class="text-sm">Model ceny<select name="pricing_model" class="mt-1 w-full rounded border p-2"><option value="fixed" @selected(old('pricing_model', $option->pricing_model) === 'fixed')>Stała kwota (zł)</option><option value="percentage" @selected(old('pricing_model', $option->pricing_model) === 'percentage')>Procent ceny bazowej</option></select></label></div>
<div class="mt-4 flex flex-wrap gap-5 text-sm"><label><input type="checkbox" name="is_required" value="1" @checked(old('is_required', $option->is_required))> Wymagana</label><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $option->exists ? $option->is_active : true))> Aktywna</label></div>
<h2 class="mt-8 text-lg font-semibold">Produkty</h2><div class="mt-3 grid max-h-48 gap-2 overflow-y-auto sm:grid-cols-2">@php($selectedProducts = old('products', $option->exists ? $option->products->pluck('id')->all() : []))@foreach($products as $product)<label class="text-sm"><input type="checkbox" name="products[]" value="{{ $product->id }}" @checked(in_array($product->id, $selectedProducts))> {{ $product->name }}</label>@endforeach</div>
<div class="mt-8 flex items-center justify-between"><h2 class="text-lg font-semibold">Wartości i dopłaty</h2><button type="button" id="add-value" class="rounded bg-slate-100 px-3 py-2 text-sm">+ Dodaj wartość</button></div><div id="values" class="mt-3 grid gap-3">@php($values = old('values', $option->exists ? $option->values->map(fn($value) => $value->toArray())->all() : [['label' => '', 'value' => '', 'price_modifier' => 0]]))@foreach($values as $index => $value)<div class="value-row grid gap-2 sm:grid-cols-[1fr_1fr_160px_auto]"><input name="values[{{ $index }}][label]" value="{{ $value['label'] ?? '' }}" placeholder="Etykieta" required class="rounded border p-2"><input name="values[{{ $index }}][value]" value="{{ $value['value'] ?? '' }}" placeholder="kod-wartosci" required class="rounded border p-2"><input name="values[{{ $index }}][price_modifier]" value="{{ $value['price_modifier'] ?? 0 }}" type="number" step="0.01" placeholder="Dopłata" required class="rounded border p-2"><button type="button" class="remove-value rounded bg-red-50 px-3 text-red-700">Usuń</button></div>@endforeach</div><button class="mt-8 rounded bg-[#D51A70] px-5 py-3 font-semibold text-white">Zapisz opcję</button></form>
<script>const values=document.getElementById('values');let index=values.querySelectorAll('.value-row').length;document.getElementById('add-value').addEventListener('click',()=>{const row=document.createElement('div');row.className='value-row grid gap-2 sm:grid-cols-[1fr_1fr_160px_auto]';row.innerHTML=`<input name="values[${index}][label]" placeholder="Etykieta" required class="rounded border p-2"><input name="values[${index}][value]" placeholder="kod-wartosci" required class="rounded border p-2"><input name="values[${index}][price_modifier]" value="0" type="number" step="0.01" required class="rounded border p-2"><button type="button" class="remove-value rounded bg-red-50 px-3 text-red-700">Usuń</button>`;values.append(row);index++});values.addEventListener('click',e=>{if(e.target.classList.contains('remove-value')&&values.querySelectorAll('.value-row').length>1)e.target.closest('.value-row').remove()});</script>
@endsection
