@extends('layouts.main')
@section('title', $order->number.' | CopyCabana')
@section('content')
<main class="cc-container" style="padding:9rem 1.5rem 6rem"><a class="text-sm text-[#D51A70]" href="{{ route('customer.orders.index') }}">← Moje zamówienia</a><div class="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-4xl font-bold">{{ $order->number }}</h1><p class="mt-2 text-slate-500">{{ $order->created_at->format('d.m.Y H:i') }}</p></div><div class="text-right"><p>{{ $order->status->label() }}</p><strong class="text-xl">{{ number_format((float) $order->total, 2, ',', ' ') }} {{ $order->currency }}</strong></div></div>
  @if(session('status'))<p class="mt-5 rounded-lg bg-green-50 p-3 text-green-800">{{ session('status') }}</p>@endif @if($errors->any())<p class="mt-5 rounded-lg bg-red-50 p-3 text-red-800">{{ $errors->first() }}</p>@endif
  <div class="mt-8 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section class="cc-local-card"><h2 class="text-2xl font-bold">Pozycje</h2><div class="mt-4 space-y-4">@foreach($order->items as $item)<div class="flex justify-between gap-4 border-b pb-3"><div><p class="font-semibold">{{ $item->product_name }}</p><p class="text-sm text-slate-500">{{ $item->quantity }} szt.</p></div><strong>{{ number_format((float) $item->total, 2, ',', ' ') }} zł</strong></div>@endforeach</div><div class="mt-5 flex justify-between"><span>Płatność</span><strong>{{ $order->payment_status }}</strong></div>
    @if(in_array($order->status->value, ['pending', 'cancelled'], true) && $order->payment_status !== 'paid')<form method="POST" action="{{ route('customer.orders.retry-payment', $order->number) }}" class="mt-5">@csrf<button class="btn-magenta" type="submit">Ponów płatność</button></form>@endif
  </section><aside class="space-y-6"><section class="cc-local-card"><h2 class="text-xl font-bold">Dokumenty</h2>@if($order->invoice)<a class="mt-3 block text-[#D51A70]" href="{{ route('customer.invoices.show', $order->invoice) }}">Faktura {{ $order->invoice->number }}</a>@endif @forelse($order->files as $file)<a class="mt-3 block text-[#D51A70]" href="{{ route('customer.orders.files.download', [$order->number, $file]) }}">Pobierz {{ $file->original_name }}</a>@empty<p class="mt-3 text-sm text-slate-500">Brak załączników.</p>@endforelse</section><section class="cc-local-card"><h2 class="text-xl font-bold">Dostawa</h2><p class="mt-3">{{ $order->shipping_method }}</p>@if($order->tracking_number)<p class="mt-2">Numer śledzenia: {{ $order->tracking_number }}</p>@if($order->trackingUrl())<a class="mt-2 block text-[#D51A70]" href="{{ $order->trackingUrl() }}" target="_blank" rel="noreferrer">Śledź przesyłkę</a>@endif @endif</section></aside></div>
</main>
@endsection
