@extends('layouts.admin')
@section('title', $order->number.' | CopyCabana')
@section('content')
<div class="flex flex-wrap items-end justify-between gap-4"><div><a class="text-sm text-[#D51A70]" href="{{ route('admin.orders.index') }}">← Zamówienia</a><h1 class="mt-2 text-3xl font-bold">{{ $order->number }}</h1><p class="text-sm text-slate-500">{{ $order->created_at->format('d.m.Y H:i') }}</p></div><a class="rounded bg-white px-3 py-2 text-sm shadow" href="{{ route('admin.orders.invoice', $order) }}" target="_blank">Faktura / wydruk</a></div>
<div class="mt-6 grid gap-6 xl:grid-cols-[2fr_1fr]">
<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Pozycje</h2><div class="mt-4 grid gap-3">@foreach($order->items as $item)<div class="flex justify-between border-b pb-3"><div><p class="font-medium">{{ $item->product_name }}</p><p class="text-sm text-slate-500">{{ $item->configuration['customer_configuration'] ?? '' }} × {{ $item->quantity }}</p></div><strong>{{ number_format((float) $item->total, 2, ',', ' ') }} zł</strong></div>@endforeach</div><div class="mt-5 flex justify-between text-lg font-bold"><span>Razem</span><span>{{ number_format((float) $order->total, 2, ',', ' ') }} zł</span></div></section>
<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Aktualizacja</h2><form method="post" action="{{ route('admin.orders.update', $order) }}" class="mt-4 grid gap-3">@csrf @method('put')<label class="text-sm">Status<select name="status" class="mt-1 w-full rounded border p-2">@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected($order->status->value === $key)>{{ $label }}</option>@endforeach</select></label><label class="text-sm">Przewoźnik<select name="carrier" class="mt-1 w-full rounded border p-2"><option value="">Brak</option>@foreach($carriers as $key => $label)<option value="{{ $key }}" @selected($order->carrier?->value === $key)>{{ $label }}</option>@endforeach</select></label><label class="text-sm">Numer śledzenia<input name="tracking_number" value="{{ $order->tracking_number }}" class="mt-1 w-full rounded border p-2"></label><label class="text-sm">Notatka<textarea name="note" class="mt-1 w-full rounded border p-2"></textarea></label><button class="rounded bg-[#D51A70] px-4 py-2 font-semibold text-white">Zapisz</button></form>@if($order->trackingUrl())<a class="mt-4 block text-sm text-[#063A60] underline" href="{{ $order->trackingUrl() }}" target="_blank">Otwórz śledzenie</a>@endif</section>
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Dane klienta</h2><dl class="mt-3 grid gap-2 text-sm"><div><dt class="text-slate-500">Imię i nazwisko</dt><dd>{{ $order->customer_name }}</dd></div><div><dt class="text-slate-500">E-mail</dt><dd>{{ $order->customer_email }}</dd></div><div><dt class="text-slate-500">Telefon</dt><dd>{{ $order->customer_phone ?: '—' }}</dd></div><div><dt class="text-slate-500">Firma / NIP</dt><dd>{{ $order->customer_company ?: '—' }} {{ $order->invoice_nip ? '/ '.$order->invoice_nip : '' }}</dd></div></dl></section><section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Historia statusu</h2><div class="mt-3 grid gap-3 text-sm">@foreach($order->statusHistories as $history)<div class="border-l-2 border-[#D51A70] pl-3"><strong>{{ $statuses[$history->to_status] ?? $history->to_status }}</strong><span class="ml-2 text-slate-500">{{ $history->created_at->format('d.m.Y H:i') }}</span>@if($history->note)<p class="text-slate-500">{{ $history->note }}</p>@endif</div>@endforeach</div></section></div>
@endsection
